# docker-compose up -d
# docker-compose down
version: "3"
services:
  producer:
    container_name: producer
    build:
      context: ./
      dockerfile: ./src/producer/Dockerfile
    env_file:
      - .env
    volumes:
      - $LOCAL_PATH:$APP_PATH

  consumer:
    container_name: consumer
    build:
      context: ./
      dockerfile: ./src/consumer/Dockerfile
    env_file:
      - .env
    volumes:
      - $LOCAL_PATH:$APP_PATH
