# docker-compose up -d
# docker-compose down
version: "3"
services:
  producer:
    container_name: producer
    build:
      context: ./
      dockerfile: ./src/producer/Dockerfile
    environment:
      SSL_CAFILE_PATH: ${SSL_CAFILE_PATH}
      SSL_CERTFILE_PATH: ${SSL_CERTFILE_PATH}
      SSL_KEYFILE_PATH: ${SSL_KEYFILE_PATH}

  consumer:
    container_name: consumer
    build:
      context: ./
      dockerfile: ./src/consumer/Dockerfile
    environment:
      SSL_CAFILE_PATH: ${SSL_CAFILE_PATH}
      SSL_CERTFILE_PATH: ${SSL_CERTFILE_PATH}
      SSL_KEYFILE_PATH: ${SSL_KEYFILE_PATH}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
